# This task performs an 'apt update', i.e. after adding new APT repositories, it is required to fetch the latest available packages before being able to install them.
---
- name: update repositories
  apt: update_cache=yes
  changed_when: False
