# This file contains additional APT repositories that will be added to /etc/apt/sources.list.d/ on Debian-based systems.
---
extra_apt_repos:
- name: Docker
  repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  key: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Keybase.io
  repo: deb https://prerelease.keybase.io/deb stable main
  key: 222B85B0F90BE2D24CFEB93F47484E50656D16C7

- name: Typora
  repo: deb http://typora.io/linux ./
  key: 4AC441BE68B4ADAB7439FBF9BA300B7755AFCFAE

- name: GitHub CLI
  repo: deb https://cli.github.com/packages {{ansible_distribution_release}} main
  key: 2CA32056ED206CB81F44A8CAC99B11DEB97541F0

- name: Tor
  repo: deb [arch=amd64] http://deb.torproject.org/torproject.org {{ansible_distribution_release}} main
  key: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89

- name: Spotify
  repo: deb http://repository.spotify.com stable non-free
  key: 8FD3D9A8D3800305A9FFF259D1742AD60D811D58

- name: KeePassXC
  repo: deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu {{ansible_distribution_release}} main
  key: D89C66D0E31FEA2874EBD20561922AB60068FCD6

- name: Mumble
  repo: deb http://ppa.launchpad.net/mumble/release/ubuntu {{ansible_distribution_release}} main
  key: 22C54CD5AAE0971730875E0285DECED27F05CF9E
